//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int EmpID { get; set; }
        public string Emp_Name { get; set; }
        public string Designation { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
    }
}
